-- Clean up existing seed data if any
DELETE FROM mentor_profiles WHERE user_id IN (SELECT id FROM users WHERE email IN ('naveen.lingala@vidhuratech.com', 'kiran.pv@vidhuratech.com', 'ranjith@vidhuratech.com', 'bhanu@vidhuratech.com'));
DELETE FROM users WHERE email IN ('naveen.lingala@vidhuratech.com', 'kiran.pv@vidhuratech.com', 'ranjith@vidhuratech.com', 'bhanu@vidhuratech.com');

-- Insert Users
INSERT INTO users (name, email, phone, password, role, active, deleted, first_login, notifications_enabled, profile_image_url, created_at)
VALUES 
('Lingala Naveen Kumar', 'naveen.lingala@vidhuratech.com', '+919988776655', '$2a$10$P/RAYcSrETx5jyR6Bdl7g.XHgN9SEPuqRcm./5Ofg0wjmOhcJYFEq', 'MENTOR', true, false, false, true, 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200&h=200', CURRENT_TIMESTAMP),
('PV Kiran', 'kiran.pv@vidhuratech.com', '+919876543210', '$2a$10$P/RAYcSrETx5jyR6Bdl7g.XHgN9SEPuqRcm./5Ofg0wjmOhcJYFEq', 'MENTOR', true, false, false, true, 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200&h=200', CURRENT_TIMESTAMP),
('Ranjith', 'ranjith@vidhuratech.com', '+918877665544', '$2a$10$P/RAYcSrETx5jyR6Bdl7g.XHgN9SEPuqRcm./5Ofg0wjmOhcJYFEq', 'MENTOR', true, false, false, true, 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200&h=200', CURRENT_TIMESTAMP),
('Bhanu', 'bhanu@vidhuratech.com', '+917766554433', '$2a$10$P/RAYcSrETx5jyR6Bdl7g.XHgN9SEPuqRcm./5Ofg0wjmOhcJYFEq', 'MENTOR', true, false, false, true, 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=200&h=200', CURRENT_TIMESTAMP);

-- Insert Mentor Profiles
INSERT INTO mentor_profiles (user_id, current_company, job_role, years_of_experience, biography, skills, languages, linkedin_url, github_url, rating, reviews_count, price_per_hour, featured, active, identity_verified, company_verified, linkedin_verified, cert_verified, terms_verified, created_at, updated_at)
VALUES 
((SELECT id FROM users WHERE email = 'naveen.lingala@vidhuratech.com'), 'Vidhura Tech', 'Java Full Stack Developer', 5.5, 'Passionate Java Full Stack Developer with over 5 years of experience in building enterprise-grade applications. Specialized in Spring Boot microservices, Angular, PostgreSQL, and modern Git workflows. I love mentoring and helping developers scale their technical skills.', 'Java, Spring Boot, Angular, Git, Hibernate, PostgreSQL, REST APIs, Microservices, TypeScript, HTML, CSS', 'English, Telugu, Hindi', 'https://linkedin.com/in/naveen-lingala', 'https://github.com/naveen-lingala', 4.9, 28, 1500.00, true, true, true, true, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM users WHERE email = 'kiran.pv@vidhuratech.com'), 'TCS', 'Automation Tester & DevOps Engineer', 6.0, 'QA Automation Lead and DevOps Practitioner. Expert in Selenium webdriver, Docker containerization, Kubernetes orchestration, AWS cloud environments, and automated CI/CD pipeline setups.', 'Selenium, TestNG, Java, Docker, Kubernetes, AWS, Jenkins, CI/CD, Git, Automation Testing, Shell Scripting', 'English, Telugu', 'https://linkedin.com/in/kiran-pv', 'https://github.com/kiran-pv', 4.8, 19, 1200.00, true, true, true, true, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM users WHERE email = 'ranjith@vidhuratech.com'), 'Cognizant', 'Salesforce & Java Developer', 4.5, 'Experienced integration expert specializing in Salesforce development (Apex, Visualforce, Lightning Web Components) and Java Spring Boot backend services. I help students cross-skill into enterprise systems.', 'Salesforce, Apex, Visualforce, Java, Spring Boot, MySQL, REST APIs, Git, Salesforce integration', 'English, Telugu, Tamil', 'https://linkedin.com/in/ranjith', 'https://github.com/ranjith', 4.7, 14, 1000.00, false, true, true, true, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
((SELECT id FROM users WHERE email = 'bhanu@vidhuratech.com'), 'Wipro', 'Python & MuleSoft Engineer', 5.0, 'Senior Systems Integrator with extensive expertise in Python frameworks (Django, Flask) and MuleSoft integration architecture. Helping students master integration patterns and API-led connectivity.', 'Python, Django, Flask, MuleSoft, AnyPoint Studio, DataWeave, REST APIs, Integration Architecture, Postgres', 'English, Telugu, Hindi', 'https://linkedin.com/in/bhanu', 'https://github.com/bhanu', 4.9, 22, 1300.00, false, true, true, true, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
