package com.vidhuratech.jobs.common.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.util.List;
import java.util.Map;

@Service
public class GeminiService {

    private final HttpClient httpClient = HttpClient.newHttpClient();
    private final ObjectMapper objectMapper = new ObjectMapper();

    @Value("${gemini.api-key:}")
    private String apiKey;

    public boolean isConfigured() {
        return apiKey != null && !apiKey.isBlank() && !apiKey.equals("YOUR_GEMINI_API_KEY_HERE");
    }

    public String getReview(String problemTitle, String problemDescription, String code, String language) {
        if (!isConfigured()) {
            return "### ⚠️ Gemini API Key not configured\n" +
                   "Please follow the **Gemini API Key Guide** to obtain an API key from Google AI Studio, " +
                   "then configure `gemini.api-key` in `application-dev.properties` to unlock real-time code assessments.";
        }

        String systemInstruction = "You are an expert AI coding companion and code reviewer for the Vidhura Tech platform.\n" +
                "Analyze the user's submitted code against the problem statement and output a concise, structured review in markdown format.\n" +
                "The review MUST contain the following sections:\n" +
                "1. **Analysis & Correctness**: Check if the code is correct, passes edge cases, and solves the problem.\n" +
                "2. **Complexity Analysis**: State the Time and Space complexity in Big O notation (e.g. O(N), O(N log N), O(1)) and explain why.\n" +
                "3. **Code Smells & Improvements**: List any issues with readability, naming conventions, redundancy, or styling.\n" +
                "4. **Optimized Alternative**: Provide a clean, fully optimized version of the code in the same language. Wrap it in a markdown code block.\n\n" +
                "Be encouraging but rigorous in your evaluation.";

        String userPrompt = String.format(
                "Problem: %s\n" +
                "Description: %s\n" +
                "Language: %s\n" +
                "User's Code:\n```%s\n%s\n```",
                problemTitle, problemDescription, language, language.toLowerCase(), code
        );

        try {
            // Package the request payload according to the Gemini API JSON structure
            Map<String, Object> parts = Map.of("text", userPrompt + "\n\nSystem Instructions:\n" + systemInstruction);
            Map<String, Object> contents = Map.of("parts", List.of(parts));
            Map<String, Object> requestBody = Map.of("contents", List.of(contents));
            String requestBodyJson = objectMapper.writeValueAsString(requestBody);

            String url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=" + apiKey;

            HttpRequest request = HttpRequest.newBuilder()
                    .uri(URI.create(url))
                    .header("Content-Type", "application/json")
                    .POST(HttpRequest.BodyPublishers.ofString(requestBodyJson))
                    .build();

            HttpResponse<String> response = httpClient.send(request, HttpResponse.BodyHandlers.ofString());

            if (response.statusCode() != 200) {
                return "❌ Gemini API error (Status Code: " + response.statusCode() + "): " + response.body();
            }

            JsonNode rootNode = objectMapper.readTree(response.body());
            JsonNode textNode = rootNode.path("candidates").get(0)
                    .path("content").path("parts").get(0).path("text");

            return textNode.asText("No review response generated by Gemini.");

        } catch (Exception e) {
            return "❌ Error communicating with Gemini API: " + e.getMessage();
        }
    }

    public String getAiHints(String problemTitle, String problemDescription, String constraints, String inputFormat, String outputFormat) {
        if (!isConfigured()) {
            return "### ⚠️ Gemini API Key not configured\n" +
                   "Please follow the **Gemini API Key Guide** to configure `gemini.api-key`.";
        }

        String systemInstruction = "You are an expert AI coding tutor.\n" +
                "Generate exactly 3 helpful, progressive hints to help a student solve the coding challenge without giving away the actual solution code.\n" +
                "Follow this strict structure for the 3 hints:\n" +
                "Hint 1 (DSA Method & Approach): Identify the core Data Structure and Algorithm (DSA) method or approach required to solve this problem (e.g., Two Pointers, Sliding Window, Dynamic Programming, Stack, Heap, Binary Search, etc.). Explain why this method fits the constraints and how to choose it.\n" +
                "Hint 2 (Step-by-Step Algorithm): Describe the step-by-step algorithmic logic in a clear, sequential manner (e.g., Step 1: ..., Step 2: ..., Step 3: ...). Walk through the solution conceptually without writing code.\n" +
                "Hint 3 (Edge Cases & Complexity): Detail crucial edge cases to consider (e.g., empty arrays, single elements, extreme boundaries, duplicates) and outline the target Time and Space Complexity (e.g., O(N) Time, O(1) Space).\n" +
                "\n" +
                "CRITICAL FORMATTING RULES:\n" +
                "1. Output exactly 3 hints, separated ONLY by a double newline (\\n\\n).\n" +
                "2. Each hint MUST be written on a single line. Do NOT use any internal newlines (\\n or \\r) inside a hint, as the frontend splits hints by any newline. Use spaces or punctuation to separate sentences.\n" +
                "3. Do NOT add any bullet points, step numbers, or numbering prefixes at the start of the hints (e.g. do not start with '1.', 'Hint 1:', etc.).\n" +
                "4. Do NOT write any code snippets or programming syntax. Use markdown bolding for emphasis on key concepts.";

        String userPrompt = String.format(
                "Problem: %s\n" +
                "Description: %s\n" +
                "Constraints: %s\n" +
                "Input Format: %s\n" +
                "Output Format: %s\n",
                problemTitle, problemDescription, constraints, inputFormat, outputFormat
        );

        try {
            Map<String, Object> parts = Map.of("text", userPrompt + "\n\nSystem Instructions:\n" + systemInstruction);
            Map<String, Object> contents = Map.of("parts", List.of(parts));
            Map<String, Object> requestBody = Map.of("contents", List.of(contents));
            String requestBodyJson = objectMapper.writeValueAsString(requestBody);

            String url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=" + apiKey;

            HttpRequest request = HttpRequest.newBuilder()
                    .uri(URI.create(url))
                    .header("Content-Type", "application/json")
                    .POST(HttpRequest.BodyPublishers.ofString(requestBodyJson))
                    .build();

            HttpResponse<String> response = httpClient.send(request, HttpResponse.BodyHandlers.ofString());

            if (response.statusCode() != 200) {
                return "Error generating hints: Gemini API error (" + response.statusCode() + ")";
            }

            JsonNode rootNode = objectMapper.readTree(response.body());
            JsonNode textNode = rootNode.path("candidates").get(0)
                    .path("content").path("parts").get(0).path("text");

            return textNode.asText("No hints response generated.");

        } catch (Exception e) {
            return "Error generating hints: " + e.getMessage();
        }
    }
}
