# DATABASE
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=3
spring.datasource.hikari.data-source-properties.sslmode=require

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# SERVER
server.port=${PORT:8080}

# LOGGING
logging.level.root=WARN
logging.level.com.vidhuratech=INFO

# REDIS
spring.data.redis.url=${REDIS_URL}
spring.data.redis.ssl.enabled=true

# FRONTEND
FRONTEND_URL=${FRONTEND_URL}

# MAIL
MAIL_HOST=${MAIL_HOST}
MAIL_PORT=${MAIL_PORT}
MAIL_USERNAME=${MAIL_USERNAME}
MAIL_PASSWORD=${MAIL_PASSWORD}

# JWT
JWT_SECRET=${JWT_SECRET}

# PAYMENT
PAYMENT_UPI_ID=${PAYMENT_UPI_ID}

# RAZORPAY
RAZORPAY_KEY=${RAZORPAY_KEY}
RAZORPAY_SECRET=${RAZORPAY_SECRET}
RAZORPAY_WEBHOOK_SECRET=${RAZORPAY_WEBHOOK_SECRET}