# DATABASE FROM ENV
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=3

# REQUIRED FOR NEON SSL
spring.datasource.hikari.data-source-properties.sslmode=require

# IMPORTANT (fix dialect error)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# SERVER
server.port=${PORT:8080}

# LOGGING (LESS NOISE)
logging.level.root=WARN
logging.level.com.vidhuratech=INFO