# LOCAL DB
spring.datasource.url=jdbc:postgresql://localhost:5432/jobsdb
spring.datasource.username=postgres
spring.datasource.password=naveen

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=3

# SERVER
server.port=8080

# LOGGING
logging.level.root=INFO
logging.level.com.vidhuratech=DEBUG