# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/jobsdb
spring.datasource.username=postgres
spring.datasource.password=naveen

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=3

# SERVER
server.port=8080

# LOGGING
logging.level.root=INFO
logging.level.com.vidhuratech=DEBUG

# REDIS
REDIS_URL=redis://localhost:6379

# FRONTEND
FRONTEND_URL=http://localhost:4200

# MAIL
MAIL_HOST=smtppro.zoho.in
MAIL_PORT=465
MAIL_USERNAME=support@vidhuratech.com
MAIL_PASSWORD=LvWBZUUA2Aks

# JWT
JWT_SECRET=local_dev_secret_123456

# PAYMENT
PAYMENT_UPI_ID=vidhuratech@axl

# RAZORPAY PAYMENT GATEWAY TEST MODE
razorpay.key=rzp_test_SfdLk9GcINVvoc
razorpay.secret=EiwQwJw0D8Nw0Og8XZv1aS11
razorpay.webhook.secret=my_webhook_secret