# APP
spring.application.name=jobs

# DATABASE (use Railway/Render provided URL)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=3

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# SERVER
server.port=${PORT:8080}

# PAGINATION
spring.data.web.pageable.default-page-size=15
spring.data.web.pageable.max-page-size=50

# CRON
scraper.cron.daily=0 0 8 * * *
scraper.cron.periodic=0 0 */6 * * *

# THREADS
spring.task.execution.pool.core-size=6
spring.task.execution.pool.max-size=12

# LOGGING (reduce in prod)
logging.level.root=WARN
logging.level.com.vidhuratech=INFO