package com.vidhuratech.jobs.lms.batch.repository;

import com.vidhuratech.jobs.lms.batch.entity.Batch;
import com.vidhuratech.jobs.lms.batch.entity.BatchStatus;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import java.util.List;
import java.util.Optional;

public interface BatchRepository extends JpaRepository<Batch, Long>, JpaSpecificationExecutor<Batch> {
   Optional<Batch> findByIdAndTrainerEmail(Long id, String email);

    Long countByTrainerEmail(String email);

    List<Batch> findByTrainerEmail(String email);

    Optional<Batch> findByName(String name);

    Optional<Batch> findTopByCourseIdOrderByStartDateDesc(Long courseId);

    @Query("""
    SELECT b FROM Batch b
    WHERE b.course.id = :courseId
    AND b.status = 'ACTIVE'
    AND b.active = true
    """)
    Optional<Batch> findActiveBatch(Long courseId);

 Optional<Batch> findTopByCourseIdAndStatusAndActiveTrueOrderByStartDateDesc(
         Long courseId,
         BatchStatus status
 );

 boolean existsByCourseIdAndBatchMonthAndAutoGeneratedTrue(Long courseId, String batchMonth);

 Optional<Batch> findTopByCourseIdAndAutoGeneratedTrueOrderByStartDateDesc(Long courseId);

 boolean existsByCourseIdAndCode(Long courseId, String code);

 Optional<Batch> findTopByCourseIdAndStatusAndActiveTrueOrderByStartDateAsc(
         Long courseId,
         BatchStatus status
 );
 @Query("""
    SELECT b FROM Batch b
    WHERE b.course.id = :courseId
    AND b.active = true
    AND b.startDate >= CURRENT_DATE
    ORDER BY b.startDate ASC
""")
 List<Batch> findUpcomingByCourseId(@Param("courseId") Long courseId, Pageable pageable);
}