package com.vidhuratech.jobs.lms.batch.service;

import com.vidhuratech.jobs.lms.batch.entity.Batch;
import com.vidhuratech.jobs.lms.batch.entity.BatchStatus;
import com.vidhuratech.jobs.lms.batch.repository.BatchRepository;
import com.vidhuratech.jobs.lms.course.entity.Course;
import com.vidhuratech.jobs.lms.course.entity.CourseStatus;
import com.vidhuratech.jobs.lms.course.entity.CourseTrainerAssignment;
import com.vidhuratech.jobs.lms.course.repository.CourseRepository;
import com.vidhuratech.jobs.lms.course.repository.CourseTrainerAssignmentRepository;
import com.vidhuratech.jobs.user.entity.User;
import com.vidhuratech.jobs.user.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;

import java.time.LocalDate;
import java.time.YearMonth;
import java.time.format.DateTimeFormatter;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Optional;

@Service
@RequiredArgsConstructor
public class MonthlyBatchGenerationService {

    private final CourseRepository courseRepository;
    private final CourseTrainerAssignmentRepository assignmentRepository;
    private final BatchRepository batchRepository;
    private final UserRepository userRepository;

    private static final DateTimeFormatter MONTH_FORMAT =
            DateTimeFormatter.ofPattern("yyyy-MM");

    @Scheduled(cron = "0 10 1 1 * ?")
    public void createMonthlyBatchesOnFirstDay() {
        createMonthlyBatchesFor(YearMonth.now());
    }

    public Map<String, Object> createMonthlyBatchesForCurrentMonth() {
        return createMonthlyBatchesFor(YearMonth.now());
    }

    public Map<String, Object> createMonthlyBatchesForNextMonth() {
        return createMonthlyBatchesFor(YearMonth.now().plusMonths(1));
    }

    public Map<String, Object> createMonthlyBatchesFor(YearMonth month) {
        int created = 0;
        int skipped = 0;

        for (Course course : courseRepository
                .findByActiveTrueAndStatusAndAutoMonthlyBatchEnabledTrue(CourseStatus.PUBLISHED)) {

            String batchMonth = month.format(MONTH_FORMAT);

            if (batchRepository.existsByCourseIdAndBatchMonthAndAutoGeneratedTrue(
                    course.getId(),
                    batchMonth
            )) {
                skipped++;
                continue;
            }

            Optional<CourseTrainerAssignment> assignment =
                    assignmentRepository.findFirstByCourseIdAndActiveTrueOrderByAssignedAtDesc(course.getId());

            if (assignment.isEmpty()) {
                skipped++;
                continue;
            }

            Optional<User> trainer = userRepository.findById(assignment.get().getTrainerId());

            if (trainer.isEmpty()) {
                skipped++;
                continue;
            }

            LocalDate startDate = month.atDay(1);
            LocalDate endDate = startDate.plusMonths(
                    course.getMonthlyBatchDurationMonths() == null
                            ? 3
                            : course.getMonthlyBatchDurationMonths()
            ).minusDays(1);

            Batch batch = Batch.builder()
                    .name(buildBatchName(course, month))
                    .course(course)
                    .trainer(trainer.get())
                    .startDate(startDate)
                    .endDate(endDate)
                    .status(BatchStatus.UPCOMING)
                    .active(true)
                    .autoGenerated(true)
                    .batchMonth(batchMonth)
                    .build();

            batchRepository.save(batch);
            created++;
        }

        Map<String, Object> result = new LinkedHashMap<>();
        result.put("month", month.format(MONTH_FORMAT));
        result.put("created", created);
        result.put("skipped", skipped);
        return result;
    }

    private String buildBatchName(Course course, YearMonth month) {
        return course.getTitle() + " - " + month.getMonth().name() + " " + month.getYear();
    }
}