ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;
ALTER TABLE users ADD CONSTRAINT users_role_check CHECK (role IN ('STUDENT', 'TRAINER', 'ADMIN', 'HR', 'MANAGER', 'SUPER_ADMIN', 'MENTOR', 'USER'));
